.TH "Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Menu" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Menu \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBHandCursor\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBMainInterface\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBMainMenu\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBOption\&.xaml\&.cs\fP"
.br
.in -1c
