.TH "Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Backup" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Backup \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBMenu\fP"
.br
.ti -1c
.RI "répertoire \fBProperties\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBApp\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBISwitchable\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBPageSwitcher\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBSwitcher\&.cs\fP"
.br
.in -1c
