.TH "Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Properties" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Properties \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBResources\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBSettings\&.Designer\&.cs\fP"
.br
.in -1c
