.TH "Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/obj/Debug" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/obj/Debug \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBMenu\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBApp\&.g\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBApp\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBGeneratedInternalTypeHelper\&.g\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBHandCursor\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBJagoanFisika_Content\&.g\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBJagoanFisika_Content\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBMainInterface\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBPageSwitcher\&.g\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBPageSwitcher\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBWindow1\&.g\&.i\&.cs\fP"
.br
.in -1c
