.TH "Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Backup/Menu" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de WPFPageSwitcher/WPFPageSwitch/Backup/Menu \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBGameplay\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBLoadGame\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBLogin\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBMainMenu\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBOption\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBRegister\&.xaml\&.cs\fP"
.br
.in -1c
