.TH "JagoanFisika.Option" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JagoanFisika.Option \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de UserControl, et \fBJagoanFisika\&.ISwitchable\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBUtilizeState\fP (object state)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
