.TH "JagoanFisika.Register" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JagoanFisika.Register \- 
.PP
Interaction logic for Register\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de UserControl\&.
.SH "Description détaillée"
.PP 
Interaction logic for Register\&.xaml 



.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
