.TH "JagoanFisika.App" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JagoanFisika.App \- 
.PP
Interaction logic for App\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Application\&.
.SH "Description détaillée"
.PP 
Interaction logic for App\&.xaml 



.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
