.TH "JagoanFisika.PageSwitcher" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JagoanFisika.PageSwitcher \- 
.PP
Interaction logic for Window1\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Window\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBNavigate\fP (UserControl nextPage)"
.br
.ti -1c
.RI "void \fBNavigate\fP (UserControl nextPage, object state)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Interaction logic for Window1\&.xaml 



.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
