.TH "JagoanFisika.Properties" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JagoanFisika.Properties \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "\fIA strongly-typed resource class, for looking up localized strings, etc\&. \fP"
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
