.TH "JagoanFisika" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JagoanFisika \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "package \fBProperties\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "\fIInteraction logic for App\&.xaml \fP"
.ti -1c
.RI "class \fBGameplay\fP"
.br
.ti -1c
.RI "interface \fBISwitchable\fP"
.br
.ti -1c
.RI "class \fBLoadGame\fP"
.br
.ti -1c
.RI "class \fBLogin\fP"
.br
.RI "\fIInteraction logic for Login\&.xaml \fP"
.ti -1c
.RI "class \fBMainMenu\fP"
.br
.ti -1c
.RI "class \fBOption\fP"
.br
.ti -1c
.RI "class \fBPageSwitcher\fP"
.br
.RI "\fIInteraction logic for Window1\&.xaml \fP"
.ti -1c
.RI "class \fBRegister\fP"
.br
.RI "\fIInteraction logic for Register\&.xaml \fP"
.ti -1c
.RI "class \fBSwitcher\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
