.TH "WPFPageSwitch.Properties" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.Properties \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "\fIUne classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées\&. \fP"
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
