.TH "WPFPageSwitch.MainMenu" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.MainMenu \- 
.PP
\fBMainMenu\fP  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de UserControl, IComponentConnector, UserControl, IComponentConnector, UserControl, et \fBWPFPageSwitch\&.ISwitchable\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBUtilizeState\fP (object state)"
.br
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SH "Description détaillée"
.PP 
\fBMainMenu\fP 


.SH "Documentation des fonctions membres"
.PP 
.SS "void WPFPageSwitch\&.MainMenu\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.MainMenu\&.InitializeComponent ()"

.PP
InitializeComponent 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
