.TH "WPFPageSwitch.PageSwitcher" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.PageSwitcher \- 
.PP
\fBPageSwitcher\fP  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Window, Window, IComponentConnector, Window, et IComponentConnector\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "\fBPageSwitcher\fP ()"
.br
.RI "\fIInitialisation du switcher et lancement du menu principal \fP"
.ti -1c
.RI "void \fBNavigate\fP (UserControl nextPage)"
.br
.RI "\fIFonction effectuant le chagement de page \fP"
.ti -1c
.RI "void \fBNavigate\fP (UserControl nextPage, object state)"
.br
.RI "\fIFonction effectuant le chagement de page \fP"
.in -1c
.SH "Description détaillée"
.PP 
\fBPageSwitcher\fP 

Interaction logic for Window\&.xaml 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "WPFPageSwitch\&.PageSwitcher\&.PageSwitcher ()"

.PP
Initialisation du switcher et lancement du menu principal 
.SH "Documentation des fonctions membres"
.PP 
.SS "void WPFPageSwitch\&.PageSwitcher\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.PageSwitcher\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.PageSwitcher\&.Navigate (UserControlnextPage)"

.PP
Fonction effectuant le chagement de page 
.PP
\fBParamètres:\fP
.RS 4
\fInextPage\fP instance vers la nouvelle page
.RE
.PP

.SS "void WPFPageSwitch\&.PageSwitcher\&.Navigate (UserControlnextPage, objectstate)"

.PP
Fonction effectuant le chagement de page 
.PP
\fBParamètres:\fP
.RS 4
\fInextPage\fP instance vers la nouvelle page
.br
\fIstate\fP 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
