.TH "WPFPageSwitch.Option" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.Option \- 
.PP
\fBOption\fP  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de UserControl, IComponentConnector, UserControl, IComponentConnector, UserControl, et \fBWPFPageSwitch\&.ISwitchable\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBUtilizeState\fP (object state)"
.br
.ti -1c
.RI "void \fBgetConfig\fP (string param, bool clear)"
.br
.RI "\fIRecuperation des donnes depuis le fichier de configurations \fP"
.ti -1c
.RI "void \fBrotate_left\fP (List< string > l)"
.br
.RI "\fIrotation d'une liste a gauche \fP"
.ti -1c
.RI "void \fBrotate_right\fP (List< string > l)"
.br
.RI "\fIrotation d'une liste a droite \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBOption\fP \fBgetInstance\fP ()"
.br
.RI "\fIRecupere une instance de la classe d'option (singleton) \fP"
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBOption\fP ()"
.br
.RI "\fIConstructeur de notre classe \fP"
.in -1c
.SS "Attributs protégés statiques"

.in +1c
.ti -1c
.RI "static \fBOption\fP \fB__instance\fP =null"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "List< string > \fBimages\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< string > \fBobj2D\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< string > \fBobj3D\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< string > \fBchapeaux\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
\fBOption\fP 


.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "WPFPageSwitch\&.Option\&.Option ()\fC [protected]\fP"

.PP
Constructeur de notre classe 
.SH "Documentation des fonctions membres"
.PP 
.SS "void WPFPageSwitch\&.Option\&.getConfig (stringparam, boolclear)"

.PP
Recuperation des donnes depuis le fichier de configurations 
.PP
\fBParamètres:\fP
.RS 4
\fIparam\fP 
.br
\fIclear\fP 
.RE
.PP

.SS "static \fBOption\fP WPFPageSwitch\&.Option\&.getInstance ()\fC [static]\fP"

.PP
Recupere une instance de la classe d'option (singleton) 
.PP
\fBRenvoie:\fP
.RS 4
instance
.RE
.PP

.SS "void WPFPageSwitch\&.Option\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.Option\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.Option\&.rotate_left (List< string >l)"

.PP
rotation d'une liste a gauche 
.PP
\fBParamètres:\fP
.RS 4
\fIl\fP 
.RE
.PP

.SS "void WPFPageSwitch\&.Option\&.rotate_right (List< string >l)"

.PP
rotation d'une liste a droite 
.PP
\fBParamètres:\fP
.RS 4
\fIl\fP 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
