.TH "WPFPageSwitch.Menu.Window1" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.Menu.Window1 \- 
.PP
\fBWindow1\fP  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Window, et IComponentConnector\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SH "Description détaillée"
.PP 
\fBWindow1\fP 


.SH "Documentation des fonctions membres"
.PP 
.SS "void WPFPageSwitch\&.Menu\&.Window1\&.InitializeComponent ()"

.PP
InitializeComponent 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
