.TH "WPFPageSwitch.HandCursor" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.HandCursor \- 
.PP
Interaction logic for HandCursor\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de UserControl, IComponentConnector, UserControl, IComponentConnector, UserControl, IComponentConnector, UserControl, et \fBWPFPageSwitch\&.ISwitchable\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBSetPosition\fP (KinectSensor kinect, Joint joint)"
.br
.RI "\fIModifie l'emplacement du curseur sur le flux video \fP"
.ti -1c
.RI "\fBCursorPoint\fP \fBGetCursorPoint\fP ()"
.br
.RI "\fIRecupere le point au centre du curseur utile pour les clics \fP"
.ti -1c
.RI "void \fBUtilizeState\fP (object state)"
.br
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SH "Description détaillée"
.PP 
Interaction logic for HandCursor\&.xaml 

\fBHandCursor\fP 
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBCursorPoint\fP WPFPageSwitch\&.HandCursor\&.GetCursorPoint ()"

.PP
Recupere le point au centre du curseur utile pour les clics 
.PP
\fBRenvoie:\fP
.RS 4
coordonne du point
.RE
.PP

.SS "void WPFPageSwitch\&.HandCursor\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.HandCursor\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.HandCursor\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.HandCursor\&.SetPosition (KinectSensorkinect, Jointjoint)"

.PP
Modifie l'emplacement du curseur sur le flux video 
.PP
\fBParamètres:\fP
.RS 4
\fIkinect\fP capteur
.br
\fIjoint\fP squelette
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
