.TH "WPFPageSwitch.GestureButton" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.GestureButton \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Button\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBGestureButton\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBGestureButton\fP class\&. \fP"
.ti -1c
.RI "bool \fBValidatePoisition\fP (\fBHandCursor\fP handCursor)"
.br
.RI "\fIValidates the poisition\&. \fP"
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "ActionStatus \fBStatus\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the status\&. \fP"
.ti -1c
.RI "\fBHandCursor\fP \fBHandCursor\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the hand cursor\&. \fP"
.in -1c
.SS "Événements"

.in +1c
.ti -1c
.RI "EventHandler< \fBActionEventArgs\fP > \fBActionEntry\fP"
.br
.RI "\fIOccurs when [action entry]\&. \fP"
.ti -1c
.RI "EventHandler< \fBActionEventArgs\fP > \fBActionExit\fP"
.br
.RI "\fIOccurs when [action exit]\&. \fP"
.ti -1c
.RI "EventHandler< \fBActionEventArgs\fP > \fBActionCompleted\fP"
.br
.RI "\fIOccurs when [action completed]\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 



.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "WPFPageSwitch\&.GestureButton\&.GestureButton ()"

.PP
Initializes a new instance of the \fBGestureButton\fP class\&. 
.SH "Documentation des fonctions membres"
.PP 
.SS "bool WPFPageSwitch\&.GestureButton\&.ValidatePoisition (\fBHandCursor\fPhandCursor)"

.PP
Validates the poisition\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIhandCursor\fP The hand cursor\&.
.RE
.PP
\fBRenvoie:\fP
.RS 4
.RE
.PP

.SH "Documentation des propriétés"
.PP 
.SS "\fBHandCursor\fP WPFPageSwitch\&.GestureButton\&.HandCursor\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the hand cursor\&. The hand cursor\&. 
.SS "ActionStatus WPFPageSwitch\&.GestureButton\&.Status\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the status\&. The status\&. 
.SH "Documentation des événements"
.PP 
.SS "EventHandler<\fBActionEventArgs\fP> WPFPageSwitch\&.GestureButton\&.ActionCompleted"

.PP
Occurs when [action completed]\&. 
.SS "EventHandler<\fBActionEventArgs\fP> WPFPageSwitch\&.GestureButton\&.ActionEntry"

.PP
Occurs when [action entry]\&. 
.SS "EventHandler<\fBActionEventArgs\fP> WPFPageSwitch\&.GestureButton\&.ActionExit"

.PP
Occurs when [action exit]\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
