.TH "WPFPageSwitch.MainInterface" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.MainInterface \- 
.PP
\fBMainInterface\fP  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de UserControl, IComponentConnector, UserControl, IComponentConnector, UserControl, IComponentConnector, UserControl, et \fBWPFPageSwitch\&.ISwitchable\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBMainInterface\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBMainWindow\fP class\&. \fP"
.ti -1c
.RI "void \fBsetImg\fP (BitmapSource bitmapS)"
.br
.RI "\fIMet une image dans le controleur d'image \fP"
.ti -1c
.RI "void \fBUtilizeState\fP (object state)"
.br
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBMainInterface\fP \fBgetInstance\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void \fBMainWindow_Loaded\fP (object sender, RoutedEventArgs e)"
.br
.RI "\fIHandles the Loaded event of the \fBMainWindow\fP control\&. \fP"
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "ActionStatus \fBStatus\fP\fC [get, set]\fP"
.br
.RI "\fIPour set ou get le statut \fP"
.ti -1c
.RI "ImageSource \fBVetementSelectionne\fP\fC [get, set]\fP"
.br
.RI "\fIVêtements \fP"
.ti -1c
.RI "ImageSource \fBChapeauSelectionne\fP\fC [get, set]\fP"
.br
.RI "\fIChapeaux \fP"
.in -1c
.SH "Description détaillée"
.PP 
\fBMainInterface\fP 


.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "WPFPageSwitch\&.MainInterface\&.MainInterface ()"

.PP
Initializes a new instance of the \fBMainWindow\fP class\&. 
.SH "Documentation des fonctions membres"
.PP 
.SS "void WPFPageSwitch\&.MainInterface\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.MainInterface\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.MainInterface\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.MainInterface\&.MainWindow_Loaded (objectsender, RoutedEventArgse)\fC [protected]\fP"

.PP
Handles the Loaded event of the \fBMainWindow\fP control\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIsender\fP The source of the event\&.
.br
\fIe\fP The System\&.Windows\&.RoutedEventArgs instance containing the event data\&.
.RE
.PP

.SS "void WPFPageSwitch\&.MainInterface\&.setImg (BitmapSourcebitmapS)"

.PP
Met une image dans le controleur d'image 
.PP
\fBParamètres:\fP
.RS 4
\fIbitmapS\fP notre image
.RE
.PP

.SH "Documentation des propriétés"
.PP 
.SS "ImageSource WPFPageSwitch\&.MainInterface\&.ChapeauSelectionne\fC [get]\fP, \fC [set]\fP"

.PP
Chapeaux 
.SS "ActionStatus WPFPageSwitch\&.MainInterface\&.Status\fC [get]\fP, \fC [set]\fP"

.PP
Pour set ou get le statut 
.SS "ImageSource WPFPageSwitch\&.MainInterface\&.VetementSelectionne\fC [get]\fP, \fC [set]\fP"

.PP
Vêtements 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
