.TH "WPFPageSwitch.SkeletonInfo" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.SkeletonInfo \- 
.PP
Information sur le squelette  

.SH SYNOPSIS
.br
.PP
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBFrameID\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the frame ID\&. \fP"
.ti -1c
.RI "Skeleton \fBSkeleton\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the skeleton\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Information sur le squelette 


.SH "Documentation des propriétés"
.PP 
.SS "int WPFPageSwitch\&.SkeletonInfo\&.FrameID\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the frame ID\&. The frame ID\&. 
.SS "Skeleton WPFPageSwitch\&.SkeletonInfo\&.Skeleton\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the skeleton\&. The skeleton\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
