.TH "WPFPageSwitch.Habits" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.Habits \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static void \fBMapJointsWithUIElement\fP (Skeleton skeleton, \fBGestionSensors\fP sensor, \fBMainInterface\fP fenetre)"
.br
.RI "\fILie les vetements avec le squelette \fP"
.in -1c
.SH "Documentation des fonctions membres"
.PP 
.SS "static void WPFPageSwitch\&.Habits\&.MapJointsWithUIElement (Skeletonskeleton, \fBGestionSensors\fPsensor, \fBMainInterface\fPfenetre)\fC [static]\fP"

.PP
Lie les vetements avec le squelette 
.PP
\fBParamètres:\fP
.RS 4
\fIskeleton\fP Skelette
.br
\fIfenetre\fP Instance vers la classe d'affichage de notre application
.br
\fIsensor\fP Entree vers les capteurs de la kinect
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
