.TH "WPFPageSwitch.App" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.App \- 
.PP
Interaction logic for App\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Application, Application, et Application\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "\fIApplication Entry Point\&. \fP"
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "\fIApplication Entry Point\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Interaction logic for App\&.xaml 

\fBApp\fP 
.SH "Documentation des fonctions membres"
.PP 
.SS "void WPFPageSwitch\&.App\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "void WPFPageSwitch\&.App\&.InitializeComponent ()"

.PP
InitializeComponent 
.SS "static void WPFPageSwitch\&.App\&.Main ()\fC [static]\fP"

.PP
Application Entry Point\&. 
.SS "static void WPFPageSwitch\&.App\&.Main ()\fC [static]\fP"

.PP
Application Entry Point\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
