.TH "WPFPageSwitch.ActionEventArgs" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch.ActionEventArgs \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de EventArgs\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBActionEventArgs\fP (ActionStatus status)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "ActionStatus \fBStatus\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
