.TH "WPFPageSwitch" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WPFPageSwitch \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "package \fBMenu\fP"
.br
.ti -1c
.RI "package \fBProperties\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionEventArgs\fP"
.br
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "\fIInteraction logic for App\&.xaml \fP"
.ti -1c
.RI "class \fBButtonExtension\fP"
.br
.RI "\fIClasse de gestion des bouton \fP"
.ti -1c
.RI "class \fBButtonPosition\fP"
.br
.RI "\fIClasse de gestion des bouton \fP"
.ti -1c
.RI "class \fBChoixChapeaux\fP"
.br
.RI "\fI\fBChoixChapeaux\fP \fP"
.ti -1c
.RI "class \fBChoixVetements\fP"
.br
.RI "\fI\fBChoixVetements\fP \fP"
.ti -1c
.RI "class \fBConfig\fP"
.br
.RI "\fIClasse permettant certaines configuration \fP"
.ti -1c
.RI "class \fBCursorPoint\fP"
.br
.RI "\fICursor Point \fP"
.ti -1c
.RI "class \fBEasyTimer\fP"
.br
.RI "\fIClasse permettant d'utiliser de maniere simple les timers \fP"
.ti -1c
.RI "class \fBGameplay\fP"
.br
.RI "\fI\fBGameplay\fP \fP"
.ti -1c
.RI "class \fBGestionSensors\fP"
.br
.RI "\fIManage sensors : Basics \fP"
.ti -1c
.RI "class \fBGestureButton\fP"
.br
.ti -1c
.RI "class \fBHabits\fP"
.br
.ti -1c
.RI "class \fBHandCursor\fP"
.br
.RI "\fIInteraction logic for HandCursor\&.xaml \fP"
.ti -1c
.RI "interface \fBISwitchable\fP"
.br
.ti -1c
.RI "class \fBLoadGame\fP"
.br
.RI "\fI\fBLoadGame\fP \fP"
.ti -1c
.RI "class \fBLogin\fP"
.br
.RI "\fI\fBLogin\fP \fP"
.ti -1c
.RI "class \fBMainInterface\fP"
.br
.RI "\fI\fBMainInterface\fP \fP"
.ti -1c
.RI "class \fBMainMenu\fP"
.br
.RI "\fI\fBMainMenu\fP \fP"
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fI\fBMainWindow\fP \fP"
.ti -1c
.RI "class \fBOption\fP"
.br
.RI "\fI\fBOption\fP \fP"
.ti -1c
.RI "class \fBPageSwitcher\fP"
.br
.RI "\fI\fBPageSwitcher\fP \fP"
.ti -1c
.RI "class \fBRegister\fP"
.br
.RI "\fI\fBRegister\fP \fP"
.ti -1c
.RI "class \fBScreenCapture\fP"
.br
.RI "\fIClasse permettant de faire des captures d'écran\&. \fP"
.ti -1c
.RI "class \fBSkeletonInfo\fP"
.br
.RI "\fIInformation sur le squelette \fP"
.ti -1c
.RI "class \fBSwitcher\fP"
.br
.RI "\fIClasse statique permettant le changement d'ihm \fP"
.ti -1c
.RI "class \fBWindow1\fP"
.br
.RI "\fI\fBWindow1\fP \fP"
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBActionStatus\fP { \fBNotStarted\fP, \fBEnter\fP, \fBExit\fP, \fBCompleted\fP }"
.br
.in -1c
.SH "Description détaillée"
.PP 
<sumary> Classe de gestions des options de notre application 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
