.TH "XamlGeneratedNamespace.GeneratedInternalTypeHelper" 3 "Dimanche 18 Mai 2014" "VirtualDressroom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XamlGeneratedNamespace.GeneratedInternalTypeHelper \- 
.PP
\fBGeneratedInternalTypeHelper\fP  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de InternalTypeHelper, et InternalTypeHelper\&.
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "override object \fBCreateInstance\fP (System\&.Type type, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "\fICreateInstance \fP"
.ti -1c
.RI "override object \fBGetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "\fIGetPropertyValue \fP"
.ti -1c
.RI "override void \fBSetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "\fISetPropertyValue \fP"
.ti -1c
.RI "override System\&.Delegate \fBCreateDelegate\fP (System\&.Type delegateType, object target, string handler)"
.br
.RI "\fICreateDelegate \fP"
.ti -1c
.RI "override void \fBAddEventHandler\fP (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)"
.br
.RI "\fIAddEventHandler \fP"
.ti -1c
.RI "override object \fBCreateInstance\fP (System\&.Type type, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "\fICreateInstance \fP"
.ti -1c
.RI "override object \fBGetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "\fIGetPropertyValue \fP"
.ti -1c
.RI "override void \fBSetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "\fISetPropertyValue \fP"
.ti -1c
.RI "override System\&.Delegate \fBCreateDelegate\fP (System\&.Type delegateType, object target, string handler)"
.br
.RI "\fICreateDelegate \fP"
.ti -1c
.RI "override void \fBAddEventHandler\fP (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)"
.br
.RI "\fIAddEventHandler \fP"
.in -1c
.SH "Description détaillée"
.PP 
\fBGeneratedInternalTypeHelper\fP 


.SH "Documentation des fonctions membres"
.PP 
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.AddEventHandler (System\&.Reflection\&.EventInfoeventInfo, objecttarget, System\&.Delegatehandler)\fC [protected]\fP"

.PP
AddEventHandler 
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.AddEventHandler (System\&.Reflection\&.EventInfoeventInfo, objecttarget, System\&.Delegatehandler)\fC [protected]\fP"

.PP
AddEventHandler 
.SS "override System\&.Delegate XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateDelegate (System\&.TypedelegateType, objecttarget, stringhandler)\fC [protected]\fP"

.PP
CreateDelegate 
.SS "override System\&.Delegate XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateDelegate (System\&.TypedelegateType, objecttarget, stringhandler)\fC [protected]\fP"

.PP
CreateDelegate 
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateInstance (System\&.Typetype, System\&.Globalization\&.CultureInfoculture)\fC [protected]\fP"

.PP
CreateInstance 
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateInstance (System\&.Typetype, System\&.Globalization\&.CultureInfoculture)\fC [protected]\fP"

.PP
CreateInstance 
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.GetPropertyValue (System\&.Reflection\&.PropertyInfopropertyInfo, objecttarget, System\&.Globalization\&.CultureInfoculture)\fC [protected]\fP"

.PP
GetPropertyValue 
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.GetPropertyValue (System\&.Reflection\&.PropertyInfopropertyInfo, objecttarget, System\&.Globalization\&.CultureInfoculture)\fC [protected]\fP"

.PP
GetPropertyValue 
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.SetPropertyValue (System\&.Reflection\&.PropertyInfopropertyInfo, objecttarget, objectvalue, System\&.Globalization\&.CultureInfoculture)\fC [protected]\fP"

.PP
SetPropertyValue 
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.SetPropertyValue (System\&.Reflection\&.PropertyInfopropertyInfo, objecttarget, objectvalue, System\&.Globalization\&.CultureInfoculture)\fC [protected]\fP"

.PP
SetPropertyValue 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VirtualDressroom à partir du code source\&.
